### ISSUE TITLE
Refresh on sub-pages loses translations

### ISSUE THREAD

**Issue by dk253** [doshprompt/angular-localization#101]
Using v1.5.0.  Works great on home page and subsequent pages until I do a refresh on a sub-page.  Then it loses its mind and finds no keys.  I may be doing something wrong, but I cant figure it out.

**Comment by bretkikehara** [comment]
please share your config. Without looking at anything, my guess is the `basePath` is a relative URL to your webapp. Try set the `basePath` URL with `/` instead of being relative to the host.

```
// http://example.com/lang/en-US/common.lang.json
// prefer this
var basePath = '/lang';

// over this
var basePath = './lang';
```

**Comment by dk253** [comment]
That did it!  Thanks!

I was following the example in the readme and just had 

> basePath: 'languages',

I guess it should be:

> basePath: '/languages',
