### ISSUE TITLE
.success is not a function

### ISSUE THREAD

**Issue by ivanstojkovicapps** [doshprompt/angular-localization#108]
Hi,

i tried with version 1.2.1, 1.5.0 and commit #104 but no success, every time i get

Error: $http.get(url)
                            .success is not a function. (In '$http.get(url)
                            .success', '$http.get(url)
                            .success' is undefined)

How to solve this?

best regards Ivan

**Comment by SiCoe** [comment]
Are you using angular 1.6 or greater?

I believe they've now taken out the depreciated `.success()` and `.error()` functions from the promise returned from `$http.get()` (and other functions called from $http).

https://code.angularjs.org/1.5.7/docs/api/ng/service/$http#deprecation-notice

It's advised to use `.then()` instead.

Guessing angular-localization will need to be updated to cope with this.

**Comment by SiCoe** [comment]
I've just had a look at angular-localization codebase.

The following merged pull request seems to cover this:

https://github.com/doshprompt/angular-localization/commit/fc8ea1535b50d3acafc26ad72dfae5e90975d706

**Comment by SiCoe** [comment]
I think this issue can only really be closed once the dist folder has been rebuilt and checked in as bower does not pick up the changes from the pull request.

**Comment by ivanstojkovicapps** [comment]
Its definitely not OK to close this, because angular-localization doesn't work with angular 1,6+

**Comment by SiCoe** [comment]
Agree, needs to be reopened.

I've see a [folk by firemondev](https://github.com/firemondev/angular-localization) that's got it built with the changes needed for angular 1.6
