### ISSUE TITLE
Load localeSupport from Remote Service

### ISSUE THREAD

**Issue by twistymcgee** [doshprompt/angular-localization#14]
I was wondering if it's possible to load the supported locales from a remote REST service. I have to define supported languages there as well so I wanted to be able to do it once. I'm just not sure how to go about setting the localeSupported value that way or if it would work at all.

**Comment by doshprompt** [comment]
@twistymcgee did @demisx's suggestion work?

**Comment by twistymcgee** [comment]
@doshprompt Sorry, I didn't get time to try it out. If/when I do I'll report back.
