### ISSUE TITLE
i18n filter doesn't work in v1.1.2

### ISSUE THREAD

**Issue by bradledbetter** [doshprompt/angular-localization#15]
I have a fairly large app in development that uses the i18n filter in angular-localization quite a bit. I was using 1.0.1 and just upgraded to 1.1.2 and the filter stopped working. The attribute directive and service still work as expected. I confirmed this behavior in the demo app included in this repository. 

I stepped into the code, and it looks like the filter fires when expected and causes the language files to load from the server, but the strings are never replaced after the language file is loaded.

I also upgraded Angular to 1.3.0 at the same time, though I don't know if that matters.

**Comment by raphox** [comment]
Thanks @doshprompt 

Im using 'ui.router' and now it is working. My code is:

```javascript
(function() {
  angular.module("ppaUi", ['ionic', 'ngLocalize', 'restangular', 'ui.router']).config([
    '$stateProvider', '$urlRouterProvider', function($stateProvider, $urlRouterProvider) {
      $stateProvider.state("home", {
        url: "/",
        templateUrl: "app/main/main.tmpl.html",
        controller: "MainCtrl"
      }).state("login", {
        url: "/login",
        templateUrl: "app/auth/auth.tmpl.html",
        controller: "LoginCtrl",
        resolve: {
          langs: function(locale) {
            return locale.ready('auth');
          }
        }
      });
      return $urlRouterProvider.otherwise('/login');
    }
  ]);

}).call(this
```

**Comment by raphox** [comment]
@doshprompt 
When I use 'locale.setLocale(loc);' occurs same problem when I dont have the resolve on stateProvider.
When I call 'locale.setLocale(loc);' only directives receive translations, in filter i18n nothing happens.

**Comment by abdheshkumar** [comment]
@doshprompt 
How can i change locale at run time by clicking on button??
Here is my code example but it's not changing locale.

app.controller('exampleCtrl', [ '$scope', 'locale', 'localeEvents',
		function($scope, locale, localeEvents) {
			$scope.changeLocale = function() {
				console.log("::::I:::::" + locale.getLocale())
					locale.setLocale("fr-FR");
				console.log("::::II:::::" + locale.getLocale())
			}
		} ]);

**Comment by doshprompt** [comment]
@abdheshkumar what version of angular are you running? Also, can you create a plunker/jsfiddle to reproduce the problem, it will be easier for me to debug there.

**Comment by ecancil** [comment]
Has this been fixed yet?  When i use your router fix i get the following error

Error: [$rootScope:inprog]
