### ISSUE TITLE
rtl support 

### ISSUE THREAD

**Issue by yong86** [doshprompt/angular-localization#22]
Does angular localization supports rtl?.I mean if i select a rtl language,the directional context of the page is shifted from right to left.

**Comment by tolbahadi** [comment]
The framework does not support that. You will need to add a locale change event handler to the direction of the document from `ltr` to `rtl`.

```js
app.run(function ($rootScope, localeEvents, locale) {
    function localeChangeHandler() {
        var currentLocale = locale.getLocale();
        if (currentLocale === 'ar-AR') {
            angular.element(document.body).attr('direction', 'rtl')
        } else {
            angular.element(document.body).attr('direction', 'ltr')
        }
    }

    $rootScope.$on(localeEvents.localeChanges, localeChangeHandler);

    // do this the first time
    localeChangeHandler();
});
```

I will be nice though, if the framework were to automatically maintain the `lang` attribute of the `html` tag to match the current locale. That way you can write you css targeting this attribute.

```css
html[lang="ar"] {
  direction: rtl;
}
html[lang="en"] {
  direction: ltr;
}
```

**Comment by doshprompt** [comment]
@tolbahadi yes I was thinking about modifying the lang attribute of the html document on localeChanges. Do you want to open a PR?
