### ISSUE TITLE
I have another question is there any way to implement locale language files to e user specific

### ISSUE THREAD

**Issue by vivdkool** [doshprompt/angular-localization#24]
i elaborate more

Suppose for default eng language i want to show "hello" to "Hi" for one user and for another "Hello".

Thanks

**Comment by doshprompt** [comment]
Doesn't seem like this is a much requested feature so as of now there is no formal support.

However, I can suggest a workaround that may suit your use case.

__example.json__

```json
{
    "helloUser1": "Hi",
    "helloUser2": "Hello",
}
```

__myController.js__

```js
angular.module('my.module')
    .controller('MyCtrl', function (user) {
        scope.user = user;
    });
```

__myView.tmpl.html__

```html
<p data-i18n="{{'example.hello' + user.id}}"></p>
```
-- OR --
```html
<p>{{('example.hello' + user.id) | i18n}}</p>
```

Then you may have to write a script which hooks into new user creation (either at the api-level or db-level)  or runs every few mins to go through the user table in your database and for each row, generates a 'hello' + <user_id> entry in your lang resource file (json)
You could also do the same thing on each app deploy but if it's not asynchronous then you might miss some users that are created in between deployments.
Currently there is no way to provide a fallback key if the one specified is not found, but if you require to have a default hello message to mitigate the issue discussed above then I may consider adding it or you could supply a PR as well.

Hope this helps, if it does work please let me know and please feel free to go ahead and close this issue as well.

**Comment by doshprompt** [comment]
Ideally, you should have those strings saved as preferences attached to the user object so you can totally bypass the localization step, as they will be hardcoded strings returned by the server.
