### ISSUE TITLE
i18n filter does not work

### ISSUE THREAD

**Issue by CrunchyArtie** [doshprompt/angular-localization#26]
It's simple, with this :

## common.lang.json

    { 
        "test" :  "Ca marche !"
    }

## ctrl.js

    $scope.strings = [];
    locale.ready('common').then(function () {
        $scope.strings.test = locale.getString('common.test');
    });

## app.js

         .value('localeConf', {
                basePath: 'languages',
                defaultLocale: 'en-US',
                sharedDictionary: 'common',
                fileExtension: '.lang.json',
                persistSelection: true,
                cookieName: 'language',
                observableAttrs: new RegExp('^data-(?!ng-|i18n)'),
                delimiter: '::'
        })
        .value('localeSupported', [
            'en-US',
            'fr-FR',
        ])
        .value('localeFallbacks', {
            'en': 'en-US',
            'fr': 'fr-FR'
        })

I can do this : 

## .html
            <ul>
                <li i18n="common.test"></li>
                <li><input data-i18n-attr="{placeholder: 'common.test'}" /></li>
                <li>{{strings.test}}</li>
            </ul>

But not this : 

## .html
     <ul>
                <li>{{ 'test' | i18n }}</li>
                <li>{{ test | i18n }}</li>
                <li>{{'common.test' | i18n}}</li>
                <li>{{common.test | i18n}}</li>
                <li ng-bind="common.test | i18n"></li>
                <li ng-bind="'common.test' | i18n"></li>
    </ul>

**Comment by sean-roberts** [comment]
+1 having the same issue.

**Comment by doshprompt** [comment]
@sean-roberts, @CrunchyArtie what version of angular are you using?

**Comment by sean-roberts** [comment]
1.3.8

**Comment by jheadley** [comment]
+1 also having this issue with Angular 1.3.13

**Comment by brycecr** [comment]
+1 with 1.3.14

**Comment by brycecr** [comment]
Attempting to figure out a bit more about this issue...

The filter is quite simple:
```
    .filter('i18n', ['locale',
        function (locale) {
            return function (input, args) {
                return locale.getString(input, args);
            };
        }
    ])
```
So if I have a page that only uses the filter, then locale.getString needs to somehow do the work of fetching and resolving mappings. 

On the first load for the filter, 
```
var result = '';
...
} else {
                        if (!bundle) {
                            loadBundle(txt);
                        }
                    }
...
return result;
```
this above is the code path taken within getLocalizedString (a.k.a. getString). loadBundle does broadcast and follow up on promises, but we haven't registered either of those. Instead we just return result, which is an empty string at this point, and are done.

So with that simpleton's view of the operation, it seems that the bundle is loaded but resolving the mapping is not paid attention to thereafter. @doshprompt , what is the expected operation after the call to `loadBundle`? Is there something/someone that should be coming by later and resolving the mapping?

**Comment by hoffbulldog** [comment]
The filter function needs to be marked as $stateful (see "Stateful filters": https://docs.angularjs.org/guide/filter).  You need a named function to do this...

```javascript
function i18nFilterFactory(LocationService) {

        function i18Filter(input, args) {
            return LocationService.getString(input, args);
        }

        i18Filter.$stateful = true;

        return i18Filter;

    }
```

**Comment by obarcelonap** [comment]
Not working using 1.4.0-rc.0
