### ISSUE TITLE
Setup defaultLanguage other than es-US for angular APP at start time

### ISSUE THREAD

**Issue by diegosanchez** [doshprompt/angular-localization#29]
Specifically I tried to setup 'es-AR' language fruitlessly. I couldn't find a way to do it even using this piece of code:

[Module setup](https://github.com/doshprompt/angular-localization#module-setup)
```
angular.module('myApp', [
    'ngLocalize',
    'ngLocalize.Config'
]).value('localeConf', {
    basePath: 'languages',
    defaultLocale: 'en-US',
    sharedDictionary: 'common',
    fileExtension: '.lang.json',
    persistSelection: true,
    cookieName: 'COOKIE_LOCALE_LANG',
    observableAttrs: new RegExp('^data-(?!ng-|i18n)'),
    delimiter: '::'
});
```

So that, I dug into the code and I found that ```defaultLocale``` is being ignored in favor of cookie value (COOKIE_LOCALE_LANG). Here: 
https://github.com/doshprompt/angular-localization/blob/master/src/localization.js#L250

If the cookieStore is already defined then the  ```defaultLocale``` is ignored because cookie value is grabbed. Supposing the cookie value is undefined then windows properties are used.

Even if I deleted the cookie the used value would be windows properties values.

This code is intended to do that. If so, there is a way to setup the language for the whole angular app?

Thanks a lot in advance

**Comment by doshprompt** [comment]
b69d76b97156b88dc0929cff958c280ab5167346
