### ISSUE TITLE
Use of i18n-attr

### ISSUE THREAD

**Issue by cdjackson** [doshprompt/angular-localization#36]
In the doc it says 
>If you want to pass dynamic values for the string, those should come after the value for each key; the series of additional parameters is expected to be appendeded to the token, prepended with a separator so that the directive will walk through and replace the numbered place holders with their values.

What does ```prepended with a separator``` mean? Can you provide an example?

Thanks

**Comment by doshprompt** [comment]
Take a look at these lines of code:

http://stackoverflow.com/questions/26170924/pascal-prechts-angular-translate-vs-rahul-doshis-angular-localization
