### ISSUE TITLE
Language Culture Name specification

### ISSUE THREAD

**Issue by gogromat** [doshprompt/angular-localization#40]
Hi.

Thank you for the great library.

It's great that library tries to follow Language Culture Name specification by Microsoft, but it is bad for people making chrome extensions.

Look at the locale table from [chrome](https://developer.chrome.com/webstore/i18n?csw=1#localeTable)

They don't support Culture Names like fr-FR or ru-RU or whatnot.

That leaves me no option but to create separate folders like 
- 'en' and 'en-US'  
- 'ru' and 'ru-RU'
just so my extension works with both chrome and angular-localization.

So can you leave option of just passing 'en' and 'ru' and 'fr'?
Previous version of this library was supporting it out of the box, don't know how this version handles it...

Sorry if I am missing something, in that case can you point me to how can I do it otherwise of making separate folders...

**Comment by cdjackson** [comment]
Can you use the fallback -:

```javascript
    .value('localeFallbacks', {
        'en': 'en-GB',
        'de': 'de-DE',
        'fr': 'fr-FR'
    })
```

the above will point any ```en``` to ```en-GB```. Maybe I don't understand your question, but can't you use this to have only a single folder for each language?

**Comment by gogromat** [comment]
So Chrome doesn't use cultural locales like fr-FR, they simply use fr, they don't use en-US, but en_US, so there are discrepancies.
So for chrome, I have a folder structure like en_US/messages.json, and for your library I had before en_US/common.json where I would put similar flat-json file.

Now, you switched to using Microsoft's spec, so I am forced to use en-US/common.json

But Chrome doesn't accept such a folder name, I cannot simply put my messages.json inside en-US/messages.json, I am forced to keep 2 different folders.

**Comment by gogromat** [comment]
That goes for any languages, like:

- Russian:  Chrome: ru/messages.json and angular-localize: ru-RU/common.json 

Instead, my desired way would be:
Chrome: ru/messages.json, angular-localize: ru/common.json

**Comment by cdjackson** [comment]
Ok - sorry. Just thought this may help. If the issue is that your version of chrome is using an underscore instead of a hyphen, why not just convert it? It’s pretty simple to change the format?

I’ve been using this library for about 6 months and it’s always been the same format - maybe it changed a long time ago, but the format it’s using is pretty standard - in my version of chrome, using ```navigator.language
``` returns ```en-US``` - the same as is used in the library.

**Comment by gogromat** [comment]
O, so you use ```navigator.language``` to detect what language to use?
So the thing is I wanted to manually select what language to present.
Like user selects language from the menu in my app, and then it is stored in local storage.
Next time I open application up, I populate the ```defaultLocale``` with that language.
So I thought your library will see what defaultLocale is set and try to load language based on that.

**Comment by cdjackson** [comment]
No - I also use a selection box - the same as you it seems. I assumed as you were saying that chrome returns ru_RU that you were using something to return the current locale. If you asking the user to select, then why not just use the format that the library uses? Maybe I’m missing something?

It seems I’m doing exactly the same as you - I store in local storage, then load on startup and call locale.setLocale(). Just use the standard format - I don’t see that chrome comes into this (unless I don’t understand something - sorry).

**Comment by gogromat** [comment]
So there is a problem with how language is being selected.

```
            if (localeConf.persistSelection && $injector.has('$cookieStore')) {
                cookieStore = $injector.get('$cookieStore');
            }
```
Here you set cookie store, if persistSelection was set to true.

Now below:

```
setLocale(cookieStore ? cookieStore.get(localeConf.cookieName) : $window.navigator.userLanguage || $window.navigator.language);
```

You just check if cookies were set, then set language from cookie. If no cookie, you take it from navigator.

In my mind, it should be like this:

```
if (cookieStore) setLocale(cookieStore.get(locale.cookieName));
else if (locale.defaultLang) setLocale(locale.defaultLang);
else setLocale($window.navigator.userLanguage || $window.navigator.language);
```

Does it make sense?

**Comment by gogromat** [comment]
So this turned to be a different problem from what I originally thought.

**Comment by cdjackson** [comment]
Maybe someone else can answer this - I don’t use the cookies - I use my own local storage and then restore the locale as I mentioned previously. I don’t detect the browser locale at all - I default to English, and then provide a select box for the user to change their language preference. I then store this using local storage (not cookies) and restore it on startup next time.

**Comment by gogromat** [comment]
Ok, I fixed my issue with

```
setLocale(cookieStore ? cookieStore.get(localeConf.cookieName) : localeConf.defaultLocale ? localeConf.defaultLocale : $window.navigator.userLanguage || $window.navigator.language);
```

Btw, what do you mean you don't use cookies? You use session cookies... $cookieStore? 
So in my case I don't have that. So either I fake $cookieStore .put/.get or fix by looking at ```localeConf.defaultLocale```. I don't want to look at ```navigator.language``` for the most part.

I will mark this issue as closed however.

Thank you for your time.

**Comment by gogromat** [comment]
p.p.s. originally I thought that en-US was selected because of the Language Culture Name specification, but it was simply coming from ```navigator.language```, although I never ever stated in ```localeSupported``` that I use 'en-US' in my app.

**Comment by cdjackson** [comment]
Glad you got it working :)


> Btw, what do you mean you don't use cookies? You use session cookies... $cookieStore? 

I use localStorage - it’s more flexible than cookies. You can store more data in it, and it doesn’t get transferred to the server.

http://www.w3schools.com/html/html5_webstorage.asp <http://www.w3schools.com/html/html5_webstorage.asp>

Cheers
Chris

**Comment by gogromat** [comment]
Your ```bower.json```:
```
  "dependencies": {
    "angular": "1.2.x",
    "angular-cookies": "1.2.x",
    "angular-sanitize": "1.2.x"
  }
```

From angular-cookies library:
```
   * @ngdoc service
   * @name $cookieStore
   * @requires $cookies
   *
   * @description
   * Provides a key-value (string-object) storage, that is backed by session cookies.
   * Objects put or retrieved from this storage are automatically serialized or
   * deserialized by angular's toJson/fromJson.
```

Ctrl+F in ```angular-cookies.js``` does nowhere shows ```Storage``` or ```sessionStorage``` or ```localStorage``` object.

From [here](https://stackoverflow.com/questions/3220660/local-storage-vs-cookies):
HTML5 has session scoped storage that can be used as a replacement for session cookies as well.

So from what I see you use session cookies and not localStorage?

**Comment by cdjackson** [comment]
No - sorry for the confusion. This is done in my application - not in the library. I’m actually not the maintainer of the library, but as I use localStorage for other things in my application I use it also for saving the locale.

**Comment by gogromat** [comment]
Right, ok.
My point was the maintainer uses cookies, which I for some reason don't have access to from an extension. Although before it seemed to work.
