### ISSUE TITLE
how to use it together with ng-message

### ISSUE THREAD

**Issue by yechongbo** [doshprompt/angular-localization#41]
Hi,

Is it able to use data-i18n directive or filter to localize ng-message?   it does not work like this. appreciate for suggestions in advance.

                <md-input-container>
                    <label data-i18n="login.username"></label>
                    <input type="text" ng-model="ViewData.UserName" name="UserName" required />
                    <div ng-messages="loginForm.UserName.$error">
                        <div ng-message="required" data-i18n="common.required">This is required.</div>
                    </div>
                </md-input-container>

**Comment by yechongbo** [comment]
wrap it up with a span

<div ng-message="required"><span data-i18n="common.required"></span></div>

**Comment by doshprompt** [comment]
Yep, @yechongbo is right ... here's an example: https://embed.plnkr.co/aYjdLRnwvfgAA251htJI/
