### ISSUE TITLE
how to make it work on windows phone 8.1 with cordova

### ISSUE THREAD

**Issue by yechongbo** [doshprompt/angular-localization#45]
it reports an error while loading language resources which is 

Error: The resource is a direct reference to a non-default resource candidate.

thanks!

**Comment by cdjackson** [comment]
I use this on Android under Cordova and there are no problems - I don't do anything special.

**Comment by yechongbo** [comment]
it's proven to be an issue related with windows packaging behaviour.  it has been fixed, thank you!
