### ISSUE TITLE
ARIA warning when localizing `aria-label` attribute

### ISSUE THREAD

**Issue by smarts** [doshprompt/angular-localization#46]
AngularJS issues a JS warning if there is no `aria-label` attribute present on certain elements
(e.g., `<md-button></md-button>`)

Is there a way to prevent the warning when using something like this?:
```html
<md-button data-i18n-attr="{'aria-label':'common.foo'}" data-i18n="common.foo"></md-button>
```

**Comment by doshprompt** [comment]
I will look into it, seems like it might be an issue with priority, let me know if you find anything then please submit a PR

**Comment by smarts** [comment]
It looks like a simple work-around is to simply add the `aria-label` attribute without any value and then the localization will substitute the correct value.

**Comment by doshprompt** [comment]
@smarts thanks, glad that there is some working fix, but I think in the long run this may be very clunky, I am looking into it but good to know that it works for your use-case in some form :)

**Comment by doshprompt** [comment]
@smarts another cleaner workaround imo is

```html
<md-button aria-label="{{'common.foo' | i18n}}" data-i18n="common.foo"></md-button>
```

**Comment by smarts** [comment]
Isn't the performance worse in that case?

**Comment by doshprompt** [comment]
@smarts yes you are right!

**Comment by doshprompt** [comment]
Fixed in https://github.com/doshprompt/angular-localization/commit/629248d40b51178326f94ef184d25996b1d4393c
