### ISSUE TITLE
Access resources as objects instead of strings

### ISSUE THREAD

**Issue by renatoch** [doshprompt/angular-localization#49]
Is there a way to access resource strings using object properties / keys instead of passing strings? 

I've tried to get access to the resource bundle, but the variable is private, so I cannot even iterate to obtain list of keys. 

This would make the code more readable, better syntax, and color coding in my text editor would be able to differentiate from regular strings in the code. 

How I use today:
```javascript
    var resourcePath = 'Document.Create';

    locale.getString(resourcePath + '.New');
```

How I would like to use:
```javascript
    var resDocCreate = locale.keys('Document.Create');

    locale.getString(resDocCreate.New); 
```

**Comment by doshprompt** [comment]
Yes I think this is possible, however, you will still need to wrap the getString in a ready promise block, will that be fine?

**Comment by renatoch** [comment]
Perhaps that wouldn't be needed. I intend to declare the variable in my controller initialization, and use locale.getString only on error messages and other stuff, which should give enough time to load all resources.

Me and a team member, @thiagoalves, were looking at promises and thread locking as a solution to another issue.
The idea is to either prevent page being shown while resources are not ready, or locking the thread once we call getString but the resource is not yet available.
This way I wouldn't need to worry about ready promise, also making the code cleaner.

Does that make sense?

**Comment by doshprompt** [comment]
@renatoch if you want to prevent the page from loading, you can utilize `locale.ready()` which returns a promise. It's fully compatible with ui-router and ng-router resolves out-of-the-box.

The only caveat is that you will have to manually maintain the list of all possible resource files that must be loaded for any route.

For example:

```js
resolve: {
  langs: function (locale) {
    return locale.ready([
      'hello',
      'world'
    ]);
  }
}
```

will block route changes until both `hello.lang.json` and `world.lang.json` have been loaded successfully.

**Comment by renatoch** [comment]
Thanks for the info! We'll try it out and let you know.
Em 01/06/2015 14:28, "Rahul Doshi" <notifications@github.com> escreveu:

**Comment by cdjackson** [comment]
I've implemented a ```getBundle()``` method to allow me to use angular-localization to load a complete bundle into another package which has its own i18n system. This might also cover the request here?

To use, you need to call -:
```js
ready("bundle").then(function(o) {
  localised_bundle = o;
})
```

**Comment by doshprompt** [comment]
You can now listen on `localeEvents.resourceUpdates` which will include the bundle
