### ISSUE TITLE
i18n filter does not work with angularjs 1.3 and 1.4

### ISSUE THREAD

**Issue by fredyang** [doshprompt/angular-localization#52]
just update bower.json file in the project by changing 1.2.x to 1.3.x to 1.4.x, the demo page will not work.

**Comment by thenikso** [comment]
It does if you pre-load the language file. I think that [here](https://github.com/doshprompt/angular-localization/blob/master/src/localization.js#L279) there should be a  `locale.ready(locale.getPath(string))...` but if there isn't there probably is a reason (that I can not understand at the moment tho).

**Comment by doshprompt** [comment]
@fredyang it should work as the filter has been marked as `$stateful` as of some time ago: efcb669ead3cea49e9a9a164782805955cef0dbd

 I have just now verified it with angular v1.3.15

@thenikso you should no longer need to resolve locale.ready anywhere, it's taken care of under the hood by angular

https://github.com/doshprompt/angular-localization/blob/master/src/localization.js#L282

For more info, see here

https://docs.angularjs.org/guide/filter#stateful-filters
http://blog.thoughtram.io/angularjs/2014/11/19/exploring-angular-1.3-stateful-filters.html
