### ISSUE TITLE
defaultLocale not working

### ISSUE THREAD

**Issue by samirgit** [doshprompt/angular-localization#57]
hello i am trying to set the default local, but it's is always using 'en-US' by default.

i have to manually call local.setLocal('fr-FR') from my controller to set to the desired language and also the selection doesn't even persist!

donno if im doing it wrong since its a straight forward task. here is my implementation : 

angular.module('myApp', [
	'ngLocalize',
	'ngLocalize.InstalledLanguages',
	'ngLocalize.Events',
	'ngLocalize.Config',

])
.value('localeSupported', [
    'en-US',
    'fr-FR',
])
.value('localeFallbacks', {
    'en': 'en-US',
    'fr':  'fr-FR',
})
.value('localeConf', {
    basePath: 'languages',
    defaultLocale: 'fr-FR',
    sharedDictionary: 'common',
    fileExtension: '.lang.json',
    persistSelection: true,
    cookieName: 'new_cookie',
    observableAttrs: new RegExp('^data-(?!ng-|i18n)'),
    delimiter: '::'
})

i have a language folder with sub-language folders...
 and logging the local inside the controller 
console.log(locale.getLocale()); always returns 'en-US', if i set it up manually by calling local.setLocal('fr-FR') the resources are updated however selection doe not persist when refreshing the browser.

persistance issue is solved by adding 'ngCookies' module to myApp

**Comment by samirgit** [comment]
everything was solved after adding 'ngCookies'

**Comment by doshprompt** [comment]
:thumbsup:
