### ISSUE TITLE
Fix "main" attribute in bower.json

### ISSUE THREAD

**Issue by tolbahadi** [doshprompt/angular-localization#58]
I think the `main` attribute in `bower.json` needs to be updated to `[ "dist/angular-localization.js", "dist/angular-localization.css"]`

Some build tools rely on this attribute to dynamically inject dependencies.

**Comment by tolbahadi** [comment]
Also the `main` attribute in `package.json` needs to be updated as well

**Comment by doshprompt** [comment]
Could you submit a PR please?

**Comment by tolbahadi** [comment]
Sure I will.
thanks
