### ISSUE TITLE
add rejection of promise if loading of bundle failed 

### ISSUE THREAD

**Issue by ladeiko** [doshprompt/angular-localization#72]
add  if (deferrences[path]) {
                                    deferrences[path].reject(data);
                                }

to:

 $http.get(url)
                            .success(function (data) {
                                var key,
                                    path = getPath(token);
                                // Merge the contents of the obtained data into the stored bundle.
                                for (key in data) {
                                    if (data.hasOwnProperty(key)) {
                                        root[key] = data[key];
                                    }
                                }

                                // Mark the bundle as having been "loaded".
                                delete root._loading;

                                // Notify anyone who cares to know about this event.
                                $rootScope.$broadcast(localeEvents.resourceUpdates);

                                // If we issued a Promise for this file, resolve it now.
                                if (deferrences[path]) {
                                    deferrences[path].resolve(path);
                                }
                            })
                            .error(function (data) {
                                $log.error("[localizationService] Failed to load: " + url);

                               if (deferrences[path]) {
                                    deferrences[path].reject(data);
                                }

                                // We can try it again later.
                                delete root._loading;
                            });

**Comment by doshprompt** [comment]
That's a good idea, could you submit a formalized PR though? It will make the diff easier for me :)

**Comment by ladeiko** [comment]
From 8223b3ddd1f5a8eb0e40d22c912587e6510db76d Mon Sep 17 00:00:00 2001
From: Siarhei Ladzeika <sergey.ladeiko@gmail.com>
Date: Sun, 15 Nov 2015 21:13:28 +0300
Subject: [PATCH] fix promise rejection

---
 src/localization.js | 7 ++++++-
 1 file changed, 6 insertions(+), 1 deletion(-)

diff --git a/src/localization.js b/src/localization.js
index f9cdad3..af5bae1 100644
--- a/src/localization.js
+++ b/src/localization.js
@@ -101,11 +101,16 @@ angular.module('ngLocalize')
                                 deferrences[path].resolve(path);
                             }
                         })
-                        .error(function () {
+                        .error(function (err) {
                             $log.error('[localizationService] Failed to load: ' + url);
 
                             // We can try it again later.
                             delete root._loading;
+                        
+                            // If we issued a Promise for this file, reject it now.
+                            if (deferrences[path]) {
+                                deferrences[path].reject(err);
+                            }
                         });
                 }
             }
-- 
2.3.2 (Apple Git-55)

**Comment by ladeiko** [comment]
[0001-fix-promise-rejection.patch.txt](https://github.com/doshprompt/angular-localization/files/34938/0001-fix-promise-rejection.patch.txt)

**Comment by doshprompt** [comment]
@ladeiko okay thanks either @bretkikehara or myself will pull this into the next release!

**Comment by bretkikehara** [comment]
Merged #80
