### ISSUE TITLE
i18n Filter Special Use-case not updating if language changes?

### ISSUE THREAD

**Issue by unruledboy** [doshprompt/angular-localization#74]
in http://doshprompt.github.io/angular-localization/ I noticed that if I change the language, it won't update  the texts. is it by design? if so, I need to use Parameterized Arguments instead?

currently I use like this to work around:

    $scope.results = {
        fooMessage: function() {
            return $filter('i18n')('demo.foo' + localeConf.delimiter + JSON.stringify({
                firstName: 'John',
                lastName: 'Smith'
            }));
        }
    };

    <div>{{results.fooMessage()}}</div>

**Comment by bretkikehara** [comment]
Please use parameters when accessing the $filter programmatically:

```javascript
var user = {
    firstName: 'John',
    lastName: 'Smith'
};
$filter('i18n')('demo.foo', user);
```
But I would highly recommend using the template filter instead! Otherwise, the `$filter` execution needs to be wrapped inside the `locale.ready` promise paradigm.

```javascript
var user = {
    firstName: 'John',
    lastName: 'Smith'
};
locale.ready('common').then(function() {
    $scope.fullName = $filter('i18n')('common.name', user);
});
```

**Recommended Usage**
```javascript
$scope.user = {
    firstName: 'John',
    lastName: 'Smith'
};
```

```html
<div>{{ demo.foo | i18n:user }}</div>
```

**Comment by doshprompt** [comment]
@unruledboy please look at @bretkikehara's comment above. Another thing to note is that if you use the `$filter('i18n')` approach in your JS you will have to manually watch for language change events and rerun your `$filter('i18n')` code to assign the newly minted string values to your scope variables.

http://doshprompt.github.io/angular-localization/##events
