### ISSUE TITLE
Refreshing a view's localized strings dynamically on language change

### ISSUE THREAD

**Issue by nick13jaremek** [doshprompt/angular-localization#81]
Hello there,

I was wondering if there is better way to update dynamically the localization of a view as soon as the locale changes.

Currently, I store the locale language in a cookie names `MY-LOCALE`, by default to `en-US`. Say the user clicks on a button to switch to the `es-ES` locale language. Right now, what I do is the following in code:

```
$cookies.put('MY-LOCALE', '"es-ES"');

$window.location.reload();
```

This changes the locale language cookie value and updates the current view. This works well, but I would like to know if it would be possible to refresh the view's localized strings without actually having to refresh the whole view.

I see there exist two events, but they seem to act like callbacks for locale changes. 

Thanks in advance for any hints.

**Comment by bretkikehara** [comment]
Yes, please look at `setLocale`. This will automatically update text in the template.

```javascript
locale.setLocale(loc);
```

The only caveat is that if the string was updated programmatically using $filter, then the reference variable must be updated as well. The [example app's footer controller](https://github.com/doshprompt/angular-localization/blob/master/app/src/shared/components/footer/footer.ctrl.js) includes a good example of updating the locale on the fly and updating data on locale change.

**Comment by nick13jaremek** [comment]
Indeed, the `setLocale` method works like a charm! I have my localized strings defined in JSON files, therefore there is no need to update any reference variables as in the footer examples. However, I will keep it as a reference for future cases.

Thank you very much @bretkikehara :smile:
