### ISSUE TITLE
Language files load after in minified code, yielding empty localized strings

### ISSUE THREAD

**Issue by nick13jaremek** [doshprompt/angular-localization#89]
Hello there,

After some struggling, I cannot seem to find a workaround to this issue. I have an Angular application with a custom module called 'localization', which "wraps" *angular-localization' as follows:
````
(function() {
    'use strict';

    angular
      .module('localization', ['ngLocalize', 'ngLocalize.Config',
          'ngLocalize.InstalledLanguages', 'ngCookies'])
      .value('localeConf', {
          basePath: './app/localization/languages',
          defaultLocale: 'en-US',
          sharedDictionary: 'common',
          fileExtension: '.lang.json',
          persistSelection: true,
          cookieName: 'CUSTOM-LOCALE',
          observableAttrs: new RegExp('^data-(?!ng-|i18n)'),
          delimiter: '::'
      })
      .value('localeSupported', [
          'en-US',
          'es-ES'
      ])
      .value('localeFallbacks', {
          'en': 'en-US',
          'es': 'es-ES'
      })
      .run(setLocaleLanguage)
      .run(runCommonLocale)
      .run(runModalsLocale);

    setLocaleLanguage.$inject = ['$window', 'locale'];
    runCommonLocale.$inject = ['locale'];
    runModalsLocale.$inject = ['locale'];

    function setLocaleLanguage($window, locale) {
        var language = $window.navigator.userLanguage || $window.navigator.language || 'en-US';
        locale.setLocale(language);
        console.log('Locale', language);
    }

    function runCommonLocale(locale) {
        console.log('common', locale);
        locale.ready('common');
    }

    function runModalsLocale(locale) {
        console.log('modals', locale);
        locale.ready('modals');
    }
})();
````

The thing is, in a development environment (**non-minified code**), the locale files specified in the **run** functions get resolved and loaded before the main view of my application is rendered. 

However, when minifying my application code and running it, I noticed that the locale files get loaded **after** every module has run and configured, and therefore, my main view's controller gets empty localized strings, which results in my view having no strings to show.

I do not know if this may be some bug related to the *angular-localization* project, or if it is related to Angular in general. I am using *ui.router*, in case it could clarify anything.

It seems like the $http requests from the *angular-localization* library get resolved after some delay in a minified code environment. 

Any help or hint regarding this problem would be greatly appreciated.

**Comment by bretkikehara** [comment]
Please paste a minimum viable example of how you access the locale strings.
This should be a template or JS code.

**Comment by nick13jaremek** [comment]
Hi there @bretkikehara 

Apart from the snippet I posted, here is how I access the locale strings in my main view controller:

````
(function() {
    'use strict';
    angular
      .module('app.home')
      .controller('MainController', mainController);

    mainController.$inject = ['$scope', 'ModalService', '$log', 'locale'];

    function mainController($scope, ModalService, $log, locale) {
        var main = this;

        main.mainLabel = locale.getString('common.makeAppointment');
        main.buttons = [
            {
                title: locale.getString('common.titleLabel'),
                action: 'show-description',
                classes: '"btn btn-default"'
            },
            {
                title: locale.getString('common.loginLabel'),
                action: 'user-login',
                classes: '"btn btn-default"'
            }];
    }
})();
````

Then, in my main view template, I access the *main* object to show the localized strings:
````
<div ng-controller="MainController">
  <h1>{{home.mainLabel}}</h1>
  <button ng-repeat="button in home.buttons" ng-class="{{button.classes}}" >
    {{button.title}}
  </button>
</div>
````

However, no labels appear on the view template.

My temporary workaround consists on loading the localized strings directly on the controller, as follows:
````
(function() {
    'use strict';
    angular
      .module('app.home')
      .controller('MainController', mainController);

    mainController.$inject = ['$scope', 'ModalService', '$log', 'locale'];

    function mainController($scope, ModalService, $log, locale) {
        var main = this;

        /* Set the labels to empty strings first */
        main.mainLabel = '';
        main.buttons = [
          {
              title: '',
              action: 'show-description',
              classes: '"btn btn-default"'
          },
          {
              title: '',
              action: 'user-login',
              classes: '"btn btn-default"'
          }];

          /* Let the locale service to load the common lang file and set the localized strings */
          locale.ready('common').then(function() {
            home.mainLabel = locale.getString('common.mainLabel');
            home.buttons[0].title = locale.getString('common.titleLabel');
            home.buttons[1].title = locale.getString('common.loginLabel');
        });
    }
})();
````

**Comment by doshprompt** [comment]
HI @nick13jaremek it looks like you are not rapping the blocks that call `locale.getString()` in your main view controller with `locale.ready()` but you are doing that in your workaround.

This is what I recommend in the original main view controller that is missing

```js
(function() {
    'use strict';
    angular
      .module('app.home')
      .controller('MainController', mainController);

    mainController.$inject = ['$scope', 'ModalService', '$log', 'locale'];

    function mainController($scope, ModalService, $log, locale) {
        var main = this;

        locale.ready('common').then(function() {
            main.mainLabel = locale.getString('common.makeAppointment');
            main.buttons = [
                {
                    title: locale.getString('common.titleLabel'),
                    action: 'show-description',
                    classes: '"btn btn-default"'
                },
                {
                    title: locale.getString('common.loginLabel'),
                    action: 'user-login',
                    classes: '"btn btn-default"'
                }
            ];
        });
    }
})();
```

Then you won't need your workaround solution. This is the right way and let me know if it works. But what would be even better is the following and this is what I personally RECOMMEND as using `locale.ready()` inside your controller is messy and should be avoided if possible.

```js
(function() {
    'use strict';
    angular
      .module('app.home')
      .controller('MainController', mainController);

    mainController.$inject = ['$scope', 'ModalService', '$log', 'locale'];

    function mainController($scope, ModalService, $log, locale) {
        var main = this;

        locale.ready('common').then(function() {
            main.mainLabel = 'common.makeAppointment';
            main.buttons = [
                {
                    title: 'common.titleLabel',
                    action: 'show-description',
                    classes: '"btn btn-default"'
                },
                {
                    title: 'common.loginLabel',
                    action: 'user-login',
                    classes: '"btn btn-default"'
                }
            ];
        });
    }
})();
```

```html
<div ng-controller="MainController">
  <h1>{{home.mainLabel | i18n }}</h1>
  <button ng-repeat="button in home.buttons" ng-class="{{button.classes}}" >
    {{ button.title | i18n }}
  </button>
</div>
```

You can read up on optimizing your page performance further using the `i18n` directive instead of the filter.

In fact, you don't even need to save a reference to mainLabel in the controller, you can just drop the token directly into the html like so:

```html
<div ng-controller="MainController">
  <h1>{{'common.makeAppointment' | i18n}}></h1>
  <button ng-repeat="button in home.buttons" ng-class="{{button.classes}}" >
    {{ button.title | i18n }}
  </button>
</div>
```

EVEN BETTER

```html
<div ng-controller="MainController">
  <h1 i18n="common.makeAppointment"></h1>
  <button ng-repeat="button in home.buttons" ng-class="{{button.classes}}" >
    {{ button.title | i18n }}
  </button>
</div>
```

Unless you need the actual strings to do some operations in the controller (not recommended btw because you will end up with giant decision ladders based on lang as you add support for more locales) you should not have to use `locale.ready()` ever.

**Comment by nick13jaremek** [comment]
Wow, thank you SO much for the detailed response @doshprompt 

Let me spend some time this week tweaking my code to match your proposed solutions. I would go with the last one, as it is easier to maintain and seems best practice.

As soon as I achieve a more efficient workaround based on your solutions, I will let you know here.

Again, thank you for the useful advices and your time :smile:

**Comment by doshprompt** [comment]
@nick13jaremek no problem, let me know if your issue is solved so I can close this.

**Comment by nick13jaremek** [comment]
Hello again @doshprompt !

I just modified my code to use your proposed solutions. In the end, I have used the the *i18n* filter like this: 

````
<div ng-controller="MainController">
  <h1 {{"common.makeAppointment" | i18n}}></h1>
</div>
````

However, I had to leave the main.buttons object in the MainController:
````
main.buttons = [
            {
                title: 'common.titleLabel',
                action: 'show-description',
                classes: '"btn btn-default"'
            },
            {
                title: 'common.loginLabel',
                action: 'user-login',
                classes: '"btn btn-default"'
            }
        ];
````

The reason for this last case is that the *main.buttons* object is passed to a directive in the MainController view, which in turn draws a series of buttons dynamically using those locale strings. Inside the directive, I changed my code to use the *i18n* filter as below:

````
<!-- Directive code-->
  <h1 {{button.title | i18n}}></h1>
</div>
````

I'm really glad there exist several solutions, most of them dealing with clean code practices. Indeed, locale strings should not be stored in the controller unless they require some manipulation there (as you mentioned). However, in this case, I had to store the *buttons* object with the locale labels to be passed on to another directive.

Thank you very much again for your dedication on this issue, and moreover on this repository. You may close this issue now :smile:
