### ISSUE TITLE
Replacement happens for the first occurence of a token

### ISSUE THREAD

**Issue by IronBy** [doshprompt/angular-localization#92]
If I have a sting in my localization file like 'Hello {name} and hello {name} again' then directive replaces only first occurence of {name} token while the second one leaves untouched.
We workaround this via additional token with the same value like 'Hello {name} and hello {sameNameAgain} again' but it looks weird.

**Comment by doshprompt** [comment]
Hi, could you send me a full example

**Comment by IronBy** [comment]
Thank you for the fix!
