### ISSUE TITLE
HTML Tags

### ISSUE THREAD

**Issue by ivanstojkovicapps** [doshprompt/angular-localization#94]
Hi,

is it possible to have something like:

`"property":"<strong>{1}</strong> my text here"`

best regards Ivan

**Comment by doshprompt** [comment]
Yes it's possible but can only be rendered correctly by the directive form.

example/property.json

```json
{
  "property": "my <strong>{text}</strong> goes here"
}
```

view template

```html
<span data-i18n="example.property" data-text="someText"></span>
```
